export {default as NavBar} from "./NavBar/NavBar"
export {default as Home } from "./Home/Home"
export {default as AboutUs } from "./AboutUs/AboutUs"
export {default as Clients } from "./Clients/Clients"
export {default as Services } from "./Services/Services"
export {default as Products } from "./Products/Products"
export {default as Testimonials } from "./Testimonials/Testimonials"
export {default as Contact } from "./Contact/Contact"
export {default as Footer } from "./Footer/Footer"